### ISSUE TITLE
brickserver unable to connect brickserver-postgres

### ISSUE THREAD

**Issue by s0301132** [BrickSchema/brick-server#5]
Hi @gtfierro and @jbkoh !

I'm using docker container to setup the brick-server, after docker-composer up all container build up successfully except brickserver, the error log said could not connect to server: Connection refused. Is the server running on host "brickserver-postgres" (172.18.0.3) and accepting TCP/IP connections on port 5432? but I check the ip of container brickserver-postgres and it match the ip as the error log. Do I need to config something to let. the brickserver connect to brickserver-postgres? There are my config.file, error log and some information:

config.json
```
{
    "timeseries": {
        "dbtype": "timescaledb",
        "dbname": "brick",
        "user": "bricker",
        "password": "brick-demo",
        "host": "brickserver-postgres",
        "port": 5432
    },
    "lockmanager": {
        "dbname": "brick",
        "user": "bricker",
        "password": "brick-demo",
        "host": "brickserver-postgres",
        "port": 5432,
        "dbtype": "postgresql"
    },
    "brick": {
        "dbtype": "virtuoso",
        "host": "http://brickserver-virtuoso:8890/sparql",
        "brick_version": "1.0.3",
        "base_ns": "bldg",
        "base_graph": "brick-base-graph"
    },
    "users": {
        "dbtype": "mongo",
        "host": "mongodb://brickserver-mongo:27017",
        "dbname": "brickserver"
    },
    "hostname": "https://YOUR_HOSTNAME.COM:8000",
    "auth": {
        "jwt": {
            "privkey_path": "/app/configs/jwtRS256.key",
            "pubkey_path": "/app/configs/jwtRS256.key.pub"
        }
    }
}
```

brickserver error log:
```
[2020-06-24 19:06:43 +0000] [11] [ERROR] Exception in worker process
brickserver             | Traceback (most recent call last):
brickserver             |   File "/usr/local/lib/python3.7/site-packages/gunicorn/arbiter.py", line 583, in spawn_worker
brickserver             |     worker.init_process()
brickserver             |   File "/usr/local/lib/python3.7/site-packages/uvicorn/workers.py", line 57, in init_process
brickserver             |     super(UvicornWorker, self).init_process()
brickserver             |   File "/usr/local/lib/python3.7/site-packages/gunicorn/workers/base.py", line 129, in init_process
brickserver             |     self.load_wsgi()
brickserver             |   File "/usr/local/lib/python3.7/site-packages/gunicorn/workers/base.py", line 138, in load_wsgi
brickserver             |     self.wsgi = self.app.wsgi()
brickserver             |   File "/usr/local/lib/python3.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
brickserver             |     self.callable = self.load()
brickserver             |   File "/usr/local/lib/python3.7/site-packages/gunicorn/app/wsgiapp.py", line 52, in load
brickserver             |     return self.load_wsgiapp()
brickserver             |   File "/usr/local/lib/python3.7/site-packages/gunicorn/app/wsgiapp.py", line 41, in load_wsgiapp
brickserver             |     return util.import_app(self.app_uri)
brickserver             |   File "/usr/local/lib/python3.7/site-packages/gunicorn/util.py", line 350, in import_app
brickserver             |     __import__(module)
brickserver             |   File "/app/main.py", line 3, in <module>
brickserver             |     from brick_server import app
brickserver             |   File "/app/brick_server/__init__.py", line 8, in <module>
brickserver             |     from .services.entities import entity_router
brickserver             |   File "/app/brick_server/services/entities.py", line 22, in <module>
brickserver             |     from ..dbs import BrickSparqlAsync
brickserver             |   File "/app/brick_server/dbs.py", line 25, in <module>
brickserver             |     lockmanager_configs['password'],
brickserver             |   File "/app/brick_server/extensions/lockmanager.py", line 21, in __init__
brickserver             |     self.conn = psycopg2.connect(conn_str)
brickserver             |   File "/usr/local/lib/python3.7/site-packages/psycopg2/__init__.py", line 126, in connect
brickserver             |     conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
brickserver             | psycopg2.OperationalError: could not connect to server: Connection refused
brickserver             | 	Is the server running on host "brickserver-postgres" (172.18.0.3) and accepting
brickserver             | 	TCP/IP connections on port 5432?
brickserver             | 
brickserver             | [2020-06-24 19:06:43 +0000] [11] [INFO] Worker exiting (pid: 11)
brickserver             | {"loglevel": "\"debug\"", "workers": 2, "bind": "0.0.0.0:80", "workers_per_core": 1.0, "host": "0.0.0.0", "port": "80"}
brickserver             | [2020-06-24 19:06:44 +0000] [10] [ERROR] Exception in worker process
brickserver             | Traceback (most recent call last):
brickserver             |   File "/usr/local/lib/python3.7/site-packages/gunicorn/arbiter.py", line 583, in spawn_worker
brickserver             |     worker.init_process()
brickserver             |   File "/usr/local/lib/python3.7/site-packages/uvicorn/workers.py", line 57, in init_process
brickserver             |     super(UvicornWorker, self).init_process()
brickserver             |   File "/usr/local/lib/python3.7/site-packages/gunicorn/workers/base.py", line 129, in init_process
brickserver             |     self.load_wsgi()
brickserver             |   File "/usr/local/lib/python3.7/site-packages/gunicorn/workers/base.py", line 138, in load_wsgi
brickserver             |     self.wsgi = self.app.wsgi()
brickserver             |   File "/usr/local/lib/python3.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
brickserver             |     self.callable = self.load()
brickserver             |   File "/usr/local/lib/python3.7/site-packages/gunicorn/app/wsgiapp.py", line 52, in load
brickserver             |     return self.load_wsgiapp()
brickserver             |   File "/usr/local/lib/python3.7/site-packages/gunicorn/app/wsgiapp.py", line 41, in load_wsgiapp
brickserver             |     return util.import_app(self.app_uri)
brickserver             |   File "/usr/local/lib/python3.7/site-packages/gunicorn/util.py", line 350, in import_app
brickserver             |     __import__(module)
brickserver             |   File "/app/main.py", line 3, in <module>
brickserver             |     from brick_server import app
brickserver             |   File "/app/brick_server/__init__.py", line 8, in <module>
brickserver             |     from .services.entities import entity_router
brickserver             |   File "/app/brick_server/services/entities.py", line 22, in <module>
brickserver             |     from ..dbs import BrickSparqlAsync
brickserver             |   File "/app/brick_server/dbs.py", line 25, in <module>
brickserver             |     lockmanager_configs['password'],
brickserver             |   File "/app/brick_server/extensions/lockmanager.py", line 21, in __init__
brickserver             |     self.conn = psycopg2.connect(conn_str)
brickserver             |   File "/usr/local/lib/python3.7/site-packages/psycopg2/__init__.py", line 126, in connect
brickserver             |     conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
brickserver             | psycopg2.OperationalError: could not connect to server: Connection refused
brickserver             | 	Is the server running on host "brickserver-postgres" (172.18.0.3) and accepting
brickserver             | 	TCP/IP connections on port 5432?
brickserver             | 
brickserver             | [2020-06-24 19:06:44 +0000] [10] [INFO] Worker exiting (pid: 10)
brickserver             | {"loglevel": "\"debug\"", "workers": 2, "bind": "0.0.0.0:80", "workers_per_core": 1.0, "host": "0.0.0.0", "port": "80"}
brickserver             | [2020-06-24 19:06:44 +0000] [1] [INFO] Shutting down: Master
brickserver             | [2020-06-24 19:06:44 +0000] [1] [INFO] Reason: Worker failed to boot.
brickserver             | {"loglevel": "\"debug\"", "workers": 2, "bind": "0.0.0.0:80", "workers_per_core": 1.0, "host": "0.0.0.0", "port": "80"}```

IP and other information about containers:
<img width="1280" alt="Screenshot 2020-06-25 at 4 03 31 AM" src="https://user-images.githubusercontent.com/47412725/85622077-ddc23d00-b698-11ea-9a4b-b9a6485e4b41.png">


Thanks a lot !

**Comment by gtfierro** [comment]
Can you post the output of `docker ps` so we can see what the port forwarding looks like?

I'm trying to get brick-server running locally but it doesn't seem that the provided default configuration works, so that'll take some effort to get working

**Comment by s0301132** [comment]
Hi @gtfierro 
There are some information about the port and ip of my container.
```
(base) Chis-MacBook-Pro:~ chihungchung$ docker ps
CONTAINER ID        IMAGE                                 COMMAND                  CREATED             STATUS              PORTS                NAMES
68bb2c84ad4d        jbkoh/brickserver-postgresql:latest   "docker-entrypoint.s…"   12 hours ago        Up 12 hours         5432/tcp             brickserver-postgres
e3e0da7d9515        tenforce/virtuoso:virtuoso7.2.5       "/bin/bash /virtuoso…"   12 hours ago        Up 12 hours         1111/tcp, 8890/tcp   brickserver-virtuoso
041dd18627ff        mongo:4.2.3-bionic                    "docker-entrypoint.s…"   12 hours ago        Up 12 hours         27017/tcp            brickserver-mongo
```

```
(base) Chis-MacBook-Pro:~ chihungchung$ docker container ls
CONTAINER ID        IMAGE                                 COMMAND                  CREATED             STATUS              PORTS                NAMES
68bb2c84ad4d        jbkoh/brickserver-postgresql:latest   "docker-entrypoint.s…"   2 minutes ago       Up 2 minutes        5432/tcp             brickserver-postgres
e3e0da7d9515        tenforce/virtuoso:virtuoso7.2.5       "/bin/bash /virtuoso…"   2 minutes ago       Up 2 minutes        1111/tcp, 8890/tcp   brickserver-virtuoso
041dd18627ff        mongo:4.2.3-bionic                    "docker-entrypoint.s…"   2 minutes ago       Up 2 minutes        27017/tcp            brickserver-mongo
```

```
(base) Chis-MacBook-Pro:~ chihungchung$ docker exec -it brickserver-postgres ifconfig
eth0      Link encap:Ethernet  HWaddr 02:42:AC:12:00:03  
          inet addr:172.18.0.3  Bcast:172.18.255.255  Mask:255.255.0.0
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:43 errors:0 dropped:0 overruns:0 frame:0
          TX packets:29 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:0 
          RX bytes:9920 (9.6 KiB)  TX bytes:3008 (2.9 KiB)

lo        Link encap:Local Loopback  
          inet addr:127.0.0.1  Mask:255.0.0.0
          UP LOOPBACK RUNNING  MTU:65536  Metric:1
          RX packets:3874 errors:0 dropped:0 overruns:0 frame:0
          TX packets:3874 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000 
          RX bytes:1329952 (1.2 MiB)  TX bytes:1329952 (1.2 MiB)

```

**Comment by s0301132** [comment]
@gtfierro may be I use the old way to install the brick server today in stead of using docker.

**Comment by gtfierro** [comment]
My current thinking is that `brickserver` is not waiting long enough for postgres to boot, and there's no retry loop within the code that reattempts to connect upon failure. If you are able to start the postgres server separately and wait for that to boot and open the socket before `brickserver` attempts to connect, that should resolve the issue.

The true fix is to include retry logic in `brickserver`, which should be pretty straightforward. It's just not clear from the documentation how the `jbkoh/brickserver` image is built, though I suspect it's the Dockerfile in the root directory of this repo

**Comment by gtfierro** [comment]
It looks like the code in the `jbkoh/brickserver` container is actually from https://gitlab.com/jbkoh/brick-server-minimal rather than this repository, and I'm not sure what else has changed between the two repos. The dependency structure in the repository is pretty unclear, so I think we have to wait for @jbkoh . Sorry!

Here's the patch of changes I was making before I discovered the repo difference: the initialization of some of the internal Brick server classes changed.

```diff
diff --git Dockerfile Dockerfile
index aec3807..50cd968 100644
--- Dockerfile
+++ Dockerfile
@@ -3,20 +3,23 @@ FROM tiangolo/uvicorn-gunicorn-fastapi:python3.7
 RUN apt update && \
     apt install -y vim certbot net-tools nmap htop
 
-ARG SRC="/usr/src/brick-server"
+#ARG SRC="./brick-server"
 
-RUN git clone https://gitlab.com/jbkoh/brick-server-minimal.git $SRC  && \
-    cd $SRC && \
-    git checkout --track origin/fastapi
+#RUN git clone https://gitlab.com/jbkoh/brick-server-minimal.git $SRC  && \
+#    cd $SRC && \
+#    git checkout --track origin/fastapi
 
-RUN rm -rf /app  && \
-    mv $SRC /app
+ADD . /app
+
+#RUN rm -rf /app  && \
+#    mv $SRC /app
+# ADD ./brick-server /app
 
 RUN pip install --upgrade pip && \
     pip install -r /app/requirements.txt && \
     pip uninstall -y fastapi && \
     pip install git+https://github.com/jbkoh/fastapi.git@fix-bodyparsing && \
-    pip install httpx
+    pip install httpx==0.12.0
 
 ENV BRICK_CONFIGFILE "/app/configs/configs.json"
 
diff --git brick_server/auth/auth_server.py brick_server/auth/auth_server.py
index 215791f..d3d136d 100644
--- brick_server/auth/auth_server.py
+++ brick_server/auth/auth_server.py
@@ -10,7 +10,8 @@ from starlette.responses import HTMLResponse, RedirectResponse, PlainTextRespons
 from starlette.requests import Request
 
 from ..configs import configs
-from .authorization import FRONTEND_APP, oauth, _get_user, authenticated, _jwt_pub_key
+# from .authorization import FRONTEND_APP, oauth, _get_user, authenticated, _jwt_pub_key
+from .authorization import FRONTEND_APP, _get_user, authenticated, _jwt_pub_key
 from .models import TokensResponse, TokenResponse
 from ..dummy_frontend import loggedin_frontend
 from ..exceptions import DoesNotExistError
diff --git brick_server/dummy_frontend.py brick_server/dummy_frontend.py
index 11d8340..60bb29f 100644
--- brick_server/dummy_frontend.py
+++ brick_server/dummy_frontend.py
@@ -7,7 +7,8 @@ from starlette.responses import HTMLResponse, RedirectResponse
 from starlette.requests import Request
 
 from .configs import configs
-from .auth.authorization import create_user, oauth
+#from .auth.authorization import create_user, oauth
+from .auth.authorization import create_user
 
 from pdb import set_trace as bp
 
diff --git requirements.txt requirements.txt
index 841a823..066896b 100644
--- requirements.txt
+++ requirements.txt
@@ -87,7 +87,7 @@ Werkzeug==0.16.1
 yarl==1.4.2
 zipp==2.2.0
 git+https://github.com/jbkoh/brick_data.git@master
-httpx
+httpx==0.12.0
 gino
 python-multipart
 pytest-env
```

**Comment by s0301132** [comment]
@gtfierro so the docker images not pulling this brick-server repo? May be I try to modify some code of `lockmanager.py`, add  some retry or sleep function to wait the postgres.

**Comment by gtfierro** [comment]
I don't think so, but it's hard to tell for sure. The Dockerfile in this repo doesn't reference this repository, so I think it's likely. If you try to modify the code, I would work off of the gitlab repo I linked above, rather than this repo.

**Comment by s0301132** [comment]
OK, also I raise this issue to gitlab, may be he can fix this issue

**Comment by jbkoh** [comment]
@s0301132 I don't see an issue with your config file. Let me merge the gitlab into here and then regenerate the problem by myself. 

In the meantime, can you check they are in the same network? I think it's correct, but just in case...

**Comment by gtfierro** [comment]
Docker compose sets up the docker network for you: I'm pretty sure this issue is caused by brickserver not waiting long enough to connect to Postgres. Even though the startup dependency is listed in the docker-compose file, it doesn't mean that the postgres sockets are listening. I've dealt with this in other projects before; inserting a brief sleep before starting brickserver (inside the entrypoint script) or implementing retry logic when connecting to postgres should fix it

**Comment by jbkoh** [comment]
brickserver waits 10 seconds once docker-compose starts: https://github.com/BrickSchema/brick-server/blob/master/docker-compose.yml.template#L37

**Comment by gtfierro** [comment]
I'm pretty sure that code never gets run....brickserver starts booting gunicorn processes immediately without sleeping, even if I change the sleep duration

**Comment by jbkoh** [comment]
@s0301132 I pushed the gitlab code into here and fixed minor issues. I wasn't able to regenerate the problem in the updated version. Please try the updated code and let me know how it goes.

@gtfierro I updated the sleep command (https://github.com/BrickSchema/brick-server/blob/master/docker-compose.yml.template#L37), which worked for me. Let me know if it still does not wait for the other containers.

**Comment by gtfierro** [comment]
Two things:

1. I think your `ENABLE_SSL` flag logic defaults to true; when I don't explicitly set that flag to FALSE in the docker-compose file, brickserver complains about not finding SSL cert files. You probably want this to default false or be more explicit about the expected behavior in the docs/comments

2. I still don't see any evidence that the sleep command is working --- brickserver is booting early and failing to connect to postgres. Are you sure that the `command` field of the docker-compose file is executed when you are building from an image?

**Comment by s0301132** [comment]
Now I can build up the `brickserver` container successfully without removing `oauth` and  `frontend` in `config.json`, thanks  @jbkoh !, the sleep function works well. I can load the documents page and will try the tutorial tomorrow.

**Comment by s0301132** [comment]
@gtfierro 
1. I face the same error before, the default flag of SSL is true, the easy way to fix this issue is uncomment the flag and set to `ENABLE_SSL=false`.

2. Have you remove the old docker images? I remove all containers and images and pull the latest version of brick-server today in github and all containers works well.

**Comment by gtfierro** [comment]
> I face the same error before, the default flag of SSL is true, the easy way to fix this issue is uncomment the flag and set to ENABLE_SSL=false.

Yep, got this to work as well --- just indicating to @jbkoh that the comment is misleading here

2. If this require removing the old docker images, then something more insidious is going on: multiple images are being distributed with the same name + version. It would be prudent to make sure that the version numbers are updated when the code is changed, else these kinds of problems will continue to arise as brick-server is updated. Removing the old docker images did fix the issue, but the versioning problem still needs to be addressed

**Comment by jbkoh** [comment]
@gtfierro @s0301132 Glad to hear the current version is working for you guys and thanks for the comments!

- I updated the docker-compose.yml.template to be more kind regarding the ssl config. 
- I will maintain proper versions of the docker image from now on. Sorry for the inconvenience.

**Comment by jbkoh** [comment]
@s0301132 Let me know if you have any other problems. Otherwise, please consider closing this Issue. Thanks!

**Comment by jli113** [comment]
This one also happens. If the images are cleared and docker-compose up for the first time, it works. Once stop and docker-compose up again, it is there.

brickserver             | [2021-07-22 13:10:40 +0000] [1] [INFO] Starting gunicorn 20.0.4
brickserver             | [2021-07-22 13:10:40 +0000] [1] [INFO] Listening at: http://0.0.0.0:80 (1)
brickserver             | [2021-07-22 13:10:40 +0000] [1] [INFO] Using worker: uvicorn.workers.UvicornWorker
brickserver             | [2021-07-22 13:10:40 +0000] [13] [INFO] Booting worker with pid: 13
brickserver             | [2021-07-22 13:10:40 +0000] [14] [INFO] Booting worker with pid: 14
brickserver             | [2021-07-22 13:10:40 +0000] [15] [INFO] Booting worker with pid: 15
brickserver             | [2021-07-22 13:10:40 +0000] [17] [INFO] Booting worker with pid: 17
brickserver             | [2021-07-22 13:10:41 +0000] [19] [INFO] Booting worker with pid: 19
brickserver             | [2021-07-22 13:10:41 +0000] [20] [INFO] Booting worker with pid: 20
brickserver             | [2021-07-22 13:10:41 +0000] [22] [INFO] Booting worker with pid: 22
brickserver             | [2021-07-22 13:10:41 +0000] [23] [INFO] Booting worker with pid: 23
brickserver             | [2021-07-22 13:10:41 +0000] [24] [INFO] Booting worker with pid: 24
brickserver             | [2021-07-22 13:10:41 +0000] [26] [INFO] Booting worker with pid: 26
brickserver             | [2021-07-22 13:10:41 +0000] [39] [INFO] Booting worker with pid: 39
brickserver             | [2021-07-22 13:10:41 +0000] [40] [INFO] Booting worker with pid: 40
brickserver             | [2021-07-22 13:10:41 +0000] [13] [INFO] Started server process [13]
brickserver             | [2021-07-22 13:10:41 +0000] [13] [INFO] Waiting for application startup.
brickserver             | [2021-07-22 13:10:41 +0000] [13] [INFO] Application startup complete.
brickserver-virtuoso    | [THREAD 0x824b7e0]:
brickserver-virtuoso    | DB.DBA.RDF_LOG_DEBUG_INFO(): initialization
brickserver-virtuoso    | [THREAD 0x8ee6290]:
brickserver-virtuoso    | DB.DBA.RDF_LOG_DEBUG_INFO(): initialization
brickserver-virtuoso    | [THREAD 0x920fa60]:
brickserver-virtuoso    | DB.DBA.RDF_LOG_DEBUG_INFO(): initialization
brickserver-virtuoso    | [THREAD 0x7b6f7b0]:
brickserver-virtuoso    | DB.DBA.RDF_LOG_DEBUG_INFO(): initialization
brickserver             | [2021-07-22 13:10:42 +0000] [14] [INFO] Started server process [14]
brickserver             | [2021-07-22 13:10:42 +0000] [14] [INFO] Waiting for application startup.
brickserver             | [2021-07-22 13:10:42 +0000] [14] [INFO] Application startup complete.
brickserver-virtuoso    | DB.DBA.RDF_LOG_DEBUG_INFO(): initialization
brickserver-virtuoso    | [THREAD 0x803c730]:
brickserver-virtuoso    | DB.DBA.RDF_LOG_DEBUG_INFO(): initialization
brickserver-virtuoso    | [THREAD 0x8ee6290]:
brickserver-virtuoso    | DB.DBA.RDF_LOG_DEBUG_INFO(): initialization
brickserver-virtuoso    | [THREAD 0x824b7e0]:
brickserver-virtuoso    | DB.DBA.RDF_LOG_DEBUG_INFO(): initialization
brickserver             | [2021-07-22 13:10:42 +0000] [15] [INFO] Started server process [15]
brickserver             | [2021-07-22 13:10:42 +0000] [15] [INFO] Waiting for application startup.
brickserver             | [2021-07-22 13:10:42 +0000] [15] [INFO] Application startup complete.
brickserver-virtuoso    | DB.DBA.RDF_LOG_DEBUG_INFO(): initialization
brickserver-virtuoso    | [THREAD 0x8ee6290]:
brickserver-virtuoso    | DB.DBA.RDF_LOG_DEBUG_INFO(): initialization
brickserver-virtuoso    | [THREAD 0x803c730]:
brickserver-virtuoso    | DB.DBA.RDF_LOG_DEBUG_INFO(): initialization
brickserver-virtuoso    | [THREAD 0x7b6f7b0]:
brickserver-virtuoso    | DB.DBA.RDF_LOG_DEBUG_INFO(): initialization
brickserver             | [2021-07-22 13:10:42 +0000] [17] [INFO] Started server process [17]
brickserver             | [2021-07-22 13:10:42 +0000] [17] [INFO] Waiting for application startup.
brickserver             | [2021-07-22 13:10:42 +0000] [17] [INFO] Application startup complete.
brickserver-virtuoso    | DB.DBA.RDF_LOG_DEBUG_INFO(): initialization
brickserver-virtuoso    | [THREAD 0x824b7e0]:
brickserver-virtuoso    | DB.DBA.RDF_LOG_DEBUG_INFO(): initialization
brickserver-virtuoso    | [THREAD 0x803c730]:
brickserver-virtuoso    | DB.DBA.RDF_LOG_DEBUG_INFO(): initialization
brickserver-virtuoso    | [THREAD 0x8ee6290]:
brickserver-virtuoso    | DB.DBA.RDF_LOG_DEBUG_INFO(): initialization
brickserver             | [2021-07-22 13:10:42 +0000] [19] [INFO] Started server process [19]
brickserver             | [2021-07-22 13:10:42 +0000] [19] [INFO] Waiting for application startup.
brickserver             | [2021-07-22 13:10:42 +0000] [19] [INFO] Application startup complete.
brickserver-virtuoso    | DB.DBA.RDF_LOG_DEBUG_INFO(): initialization
brickserver-virtuoso    | [THREAD 0x803c730]:
brickserver-virtuoso    | DB.DBA.RDF_LOG_DEBUG_INFO(): initialization
brickserver-virtuoso    | [THREAD 0x7b6f7b0]:
brickserver-virtuoso    | DB.DBA.RDF_LOG_DEBUG_INFO(): initialization
brickserver-virtuoso    | [THREAD 0x824b7e0]:
brickserver-virtuoso    | DB.DBA.RDF_LOG_DEBUG_INFO(): initialization
brickserver             | [2021-07-22 13:10:42 +0000] [20] [INFO] Started server process [20]
brickserver             | [2021-07-22 13:10:42 +0000] [20] [INFO] Waiting for application startup.
brickserver             | [2021-07-22 13:10:42 +0000] [20] [INFO] Application startup complete.
brickserver-virtuoso    | DB.DBA.RDF_LOG_DEBUG_INFO(): initialization
brickserver-virtuoso    | [THREAD 0x7b6f7b0]:
brickserver-virtuoso    | DB.DBA.RDF_LOG_DEBUG_INFO(): initialization
brickserver-virtuoso    | [THREAD 0x803c730]:
brickserver-virtuoso    | DB.DBA.RDF_LOG_DEBUG_INFO(): initialization
brickserver-virtuoso    | [THREAD 0x8ee6290]:
brickserver-virtuoso    | DB.DBA.RDF_LOG_DEBUG_INFO(): initialization
brickserver             | [2021-07-22 13:10:42 +0000] [26] [INFO] Started server process [26]
brickserver             | [2021-07-22 13:10:42 +0000] [26] [INFO] Waiting for application startup.
brickserver             | [2021-07-22 13:10:42 +0000] [26] [INFO] Application startup complete.
brickserver-virtuoso    | [THREAD 0x824b7e0]:
brickserver-virtuoso    | DB.DBA.RDF_LOG_DEBUG_INFO(): initialization
brickserver-virtuoso    | [THREAD 0x7b6f7b0]:
brickserver-virtuoso    | DB.DBA.RDF_LOG_DEBUG_INFO(): initialization
brickserver-virtuoso    | [THREAD 0x8ee6290]:
brickserver-virtuoso    | DB.DBA.RDF_LOG_DEBUG_INFO(): initialization
brickserver-virtuoso    | [THREAD 0x803c730]:
brickserver-virtuoso    | DB.DBA.RDF_LOG_DEBUG_INFO(): initialization
brickserver             | [2021-07-22 13:10:42 +0000] [24] [INFO] Started server process [24]
brickserver             | [2021-07-22 13:10:42 +0000] [24] [INFO] Waiting for application startup.
brickserver             | [2021-07-22 13:10:42 +0000] [22] [INFO] Started server process [22]
brickserver             | [2021-07-22 13:10:42 +0000] [22] [INFO] Waiting for application startup.
brickserver             | [2021-07-22 13:10:42 +0000] [24] [INFO] Application startup complete.
brickserver-virtuoso    | [THREAD 0x8ee6290]:
brickserver-virtuoso    | DB.DBA.RDF_LOG_DEBUG_INFO(): initialization
brickserver-virtuoso    | [THREAD 0x824b7e0]:
brickserver-virtuoso    | DB.DBA.RDF_LOG_DEBUG_INFO(): initialization
brickserver-virtuoso    | [THREAD 0x803c730]:
brickserver-virtuoso    | DB.DBA.RDF_LOG_DEBUG_INFO(): initialization
brickserver-virtuoso    | [THREAD 0x7b6f7b0]:
brickserver-virtuoso    | DB.DBA.RDF_LOG_DEBUG_INFO(): initialization
brickserver             | [2021-07-22 13:10:42 +0000] [22] [INFO] Application startup complete.
brickserver-virtuoso    | DB.DBA.RDF_LOG_DEBUG_INFO(): initialization
brickserver-virtuoso    | [THREAD 0x803c730]:
brickserver-virtuoso    | DB.DBA.RDF_LOG_DEBUG_INFO(): initialization
brickserver-virtuoso    | [THREAD 0x824b7e0]:
brickserver-virtuoso    | DB.DBA.RDF_LOG_DEBUG_INFO(): initialization
brickserver-virtuoso    | [THREAD 0x8ee6290]:
brickserver-virtuoso    | DB.DBA.RDF_LOG_DEBUG_INFO(): initialization
brickserver             | [2021-07-22 13:10:42 +0000] [23] [INFO] Started server process [23]
brickserver             | [2021-07-22 13:10:42 +0000] [23] [INFO] Waiting for application startup.
brickserver-postgres    | 2021-07-22 13:10:42.959 UTC [131] FATAL:  sorry, too many clients already
brickserver             | Task exception was never retrieved
brickserver             | future: <Task finished coro=<AsyncpgTimeseries.init() done, defined at /usr/local/lib/python3.7/site-packages/brick_data/timeseries/asyncpg_wrapper.py:51> exception=TooManyConnectionsError('sorry, too many clients already')>
brickserver             | Traceback (most recent call last):
brickserver             |   File "/usr/local/lib/python3.7/site-packages/brick_data/timeseries/asyncpg_wrapper.py", line 52, in init
brickserver             |     self.pool = await asyncpg.create_pool(dsn=self.conn_str, **pool_config)
brickserver             |   File "/usr/local/lib/python3.7/site-packages/asyncpg/pool.py", line 398, in _async__init__
brickserver             |     await self._initialize()
brickserver             |   File "/usr/local/lib/python3.7/site-packages/asyncpg/pool.py", line 436, in _initialize
brickserver             |     await asyncio.gather(*connect_tasks)
brickserver             |   File "/usr/local/lib/python3.7/site-packages/asyncpg/pool.py", line 125, in connect
brickserver             |     self._con = await self._pool._get_new_connection()
brickserver             |   File "/usr/local/lib/python3.7/site-packages/asyncpg/pool.py", line 487, in _get_new_connection
brickserver             |     connection_class=self._connection_class)
brickserver             |   File "/usr/local/lib/python3.7/site-packages/asyncpg/connect_utils.py", line 631, in _connect_addr
brickserver             |     await asyncio.wait_for(connected, timeout=timeout)
brickserver             |   File "/usr/local/lib/python3.7/asyncio/tasks.py", line 442, in wait_for
brickserver             |     return fut.result()
brickserver             | asyncpg.exceptions.TooManyConnectionsError: sorry, too many clients already
brickserver             | [2021-07-22 13:10:42 +0000] [23] [INFO] Application startup complete.
brickserver-postgres    | 2021-07-22 13:10:42.963 UTC [135] FATAL:  sorry, too many clients already
brickserver-virtuoso    | DB.DBA.RDF_LOG_DEBUG_INFO(): initialization
brickserver             | Task exception was never retrieved
brickserver             | future: <Task finished coro=<AsyncpgTimeseries.init() done, defined at /usr/local/lib/python3.7/site-packages/brick_data/timeseries/asyncpg_wrapper.py:51> exception=TooManyConnectionsError('sorry, too many clients already')>
brickserver             | Traceback (most recent call last):
brickserver             |   File "/usr/local/lib/python3.7/site-packages/brick_data/timeseries/asyncpg_wrapper.py", line 52, in init
brickserver             |     self.pool = await asyncpg.create_pool(dsn=self.conn_str, **pool_config)
brickserver             |   File "/usr/local/lib/python3.7/site-packages/asyncpg/pool.py", line 398, in _async__init__
brickserver             |     await self._initialize()
brickserver             |   File "/usr/local/lib/python3.7/site-packages/asyncpg/pool.py", line 426, in _initialize
brickserver             |     await first_ch.connect()
brickserver             |   File "/usr/local/lib/python3.7/site-packages/asyncpg/pool.py", line 125, in connect
brickserver             |     self._con = await self._pool._get_new_connection()
brickserver             |   File "/usr/local/lib/python3.7/site-packages/asyncpg/pool.py", line 472, in _get_new_connection
brickserver             |     **self._connect_kwargs)
brickserver             |   File "/usr/local/lib/python3.7/site-packages/asyncpg/connection.py", line 1677, in connect
brickserver             |     max_cacheable_statement_size=max_cacheable_statement_size)
brickserver             |   File "/usr/local/lib/python3.7/site-packages/asyncpg/connect_utils.py", line 655, in _connect
brickserver             |     connection_class=connection_class)
brickserver             |   File "/usr/local/lib/python3.7/site-packages/asyncpg/connect_utils.py", line 631, in _connect_addr
brickserver             |     await asyncio.wait_for(connected, timeout=timeout)
brickserver             |   File "/usr/local/lib/python3.7/asyncio/tasks.py", line 442, in wait_for
brickserver             |     return fut.result()
brickserver             | asyncpg.exceptions.TooManyConnectionsError: sorry, too many clients already
brickserver-virtuoso    | [THREAD 0x7b6f7b0]:
brickserver-virtuoso    | DB.DBA.RDF_LOG_DEBUG_INFO(): initialization
brickserver-virtuoso    | [THREAD 0x824b7e0]:
brickserver-virtuoso    | DB.DBA.RDF_LOG_DEBUG_INFO(): initialization
brickserver-virtuoso    | [THREAD 0x803c730]:
brickserver-virtuoso    | DB.DBA.RDF_LOG_DEBUG_INFO(): initialization
brickserver             | [2021-07-22 13:10:42 +0000] [40] [INFO] Started server process [40]
brickserver             | [2021-07-22 13:10:42 +0000] [40] [INFO] Waiting for application startup.
brickserver             | [2021-07-22 13:10:42 +0000] [40] [INFO] Application startup complete.
brickserver-postgres    | 2021-07-22 13:10:42.983 UTC [136] FATAL:  sorry, too many clients already
brickserver-virtuoso    | DB.DBA.RDF_LOG_DEBUG_INFO(): initialization
brickserver             | Task exception was never retrieved
brickserver             | future: <Task finished coro=<AsyncpgTimeseries.init() done, defined at /usr/local/lib/python3.7/site-packages/brick_data/timeseries/asyncpg_wrapper.py:51> exception=TooManyConnectionsError('sorry, too many clients already')>
brickserver             | Traceback (most recent call last):
brickserver             |   File "/usr/local/lib/python3.7/site-packages/brick_data/timeseries/asyncpg_wrapper.py", line 52, in init
brickserver             |     self.pool = await asyncpg.create_pool(dsn=self.conn_str, **pool_config)
brickserver             |   File "/usr/local/lib/python3.7/site-packages/asyncpg/pool.py", line 398, in _async__init__
brickserver             |     await self._initialize()
brickserver             |   File "/usr/local/lib/python3.7/site-packages/asyncpg/pool.py", line 426, in _initialize
brickserver             |     await first_ch.connect()
brickserver             |   File "/usr/local/lib/python3.7/site-packages/asyncpg/pool.py", line 125, in connect
brickserver             |     self._con = await self._pool._get_new_connection()
brickserver             |   File "/usr/local/lib/python3.7/site-packages/asyncpg/pool.py", line 472, in _get_new_connection
brickserver             |     **self._connect_kwargs)
brickserver             |   File "/usr/local/lib/python3.7/site-packages/asyncpg/connection.py", line 1677, in connect
brickserver             |     max_cacheable_statement_size=max_cacheable_statement_size)
brickserver             |   File "/usr/local/lib/python3.7/site-packages/asyncpg/connect_utils.py", line 655, in _connect
brickserver             |     connection_class=connection_class)
brickserver             |   File "/usr/local/lib/python3.7/site-packages/asyncpg/connect_utils.py", line 631, in _connect_addr
brickserver             |     await asyncio.wait_for(connected, timeout=timeout)
brickserver             |   File "/usr/local/lib/python3.7/asyncio/tasks.py", line 442, in wait_for
brickserver             |     return fut.result()
brickserver             | asyncpg.exceptions.TooManyConnectionsError: sorry, too many clients already
brickserver-virtuoso    | [THREAD 0x7b6f7b0]:
brickserver-virtuoso    | DB.DBA.RDF_LOG_DEBUG_INFO(): initialization
brickserver-virtuoso    | [THREAD 0x824b7e0]:
brickserver-virtuoso    | DB.DBA.RDF_LOG_DEBUG_INFO(): initialization
brickserver-virtuoso    | [THREAD 0x8ee6290]:
brickserver-virtuoso    | DB.DBA.RDF_LOG_DEBUG_INFO(): initialization
brickserver-postgres    | 2021-07-22 13:10:43.006 UTC [137] FATAL:  sorry, too many clients already
brickserver             | [2021-07-22 13:10:43 +0000] [39] [ERROR] Exception in worker process
brickserver             | Traceback (most recent call last):
brickserver             |   File "/usr/local/lib/python3.7/site-packages/gunicorn/arbiter.py", line 583, in spawn_worker
brickserver             |     worker.init_process()
brickserver             |   File "/usr/local/lib/python3.7/site-packages/uvicorn/workers.py", line 57, in init_process
brickserver             |     super(UvicornWorker, self).init_process()
brickserver             |   File "/usr/local/lib/python3.7/site-packages/gunicorn/workers/base.py", line 119, in init_process
brickserver             |     self.load_wsgi()
brickserver             |   File "/usr/local/lib/python3.7/site-packages/gunicorn/workers/base.py", line 144, in load_wsgi
brickserver             |     self.wsgi = self.app.wsgi()
brickserver             |   File "/usr/local/lib/python3.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
brickserver             |     self.callable = self.load()
brickserver             |   File "/usr/local/lib/python3.7/site-packages/gunicorn/app/wsgiapp.py", line 49, in load
brickserver             |     return self.load_wsgiapp()
brickserver             |   File "/usr/local/lib/python3.7/site-packages/gunicorn/app/wsgiapp.py", line 39, in load_wsgiapp
brickserver             |     return util.import_app(self.app_uri)
brickserver             |   File "/usr/local/lib/python3.7/site-packages/gunicorn/util.py", line 358, in import_app
brickserver             |     mod = importlib.import_module(module)
brickserver             |   File "/usr/local/lib/python3.7/importlib/__init__.py", line 127, in import_module
brickserver             |     return _bootstrap._gcd_import(name[level:], package, level)
brickserver             |   File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
brickserver             |   File "<frozen importlib._bootstrap>", line 983, in _find_and_load
brickserver             |   File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
brickserver             |   File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
brickserver             |   File "<frozen importlib._bootstrap_external>", line 728, in exec_module
brickserver             |   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
brickserver             |   File "/app/main.py", line 3, in <module>
brickserver             |     from brick_server import app
brickserver             |   File "/app/brick_server/__init__.py", line 8, in <module>
brickserver             |     from .services.entities import entity_router
brickserver             |   File "/app/brick_server/services/entities.py", line 22, in <module>
brickserver             |     from ..dbs import BrickSparqlAsync
brickserver             |   File "/app/brick_server/dbs.py", line 26, in <module>
brickserver             |     lockmanager_configs['password'],
brickserver             |   File "/app/brick_server/extensions/lockmanager.py", line 21, in __init__
brickserver             |     self.conn = psycopg2.connect(conn_str)
brickserver             |   File "/usr/local/lib/python3.7/site-packages/psycopg2/__init__.py", line 126, in connect
brickserver             |     conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
brickserver             | psycopg2.OperationalError: FATAL:  sorry, too many clients already
brickserver             | 
brickserver             | [2021-07-22 13:10:43 +0000] [39] [INFO] Worker exiting (pid: 39)
brickserver             | {"loglevel": "\"debug\"", "workers": 12, "bind": "0.0.0.0:80", "graceful_timeout": 120, "timeout": 120, "keepalive": 5, "errorlog": "-", "accesslog": "-", "workers_per_core": 1.0, "use_max_workers": null, "host": "0.0.0.0", "port": "80"}
brickserver             | [2021-07-22 13:10:43 +0000] [17] [INFO] Shutting down
brickserver             | [2021-07-22 13:10:43 +0000] [26] [INFO] Shutting down
brickserver             | [2021-07-22 13:10:43 +0000] [19] [INFO] Shutting down
brickserver             | [2021-07-22 13:10:43 +0000] [24] [INFO] Shutting down
brickserver             | [2021-07-22 13:10:43 +0000] [22] [INFO] Shutting down
brickserver             | [2021-07-22 13:10:43 +0000] [20] [INFO] Shutting down
brickserver             | [2021-07-22 13:10:43 +0000] [13] [INFO] Shutting down
brickserver             | [2021-07-22 13:10:43 +0000] [14] [INFO] Shutting down
brickserver             | [2021-07-22 13:10:43 +0000] [23] [INFO] Shutting down
brickserver             | [2021-07-22 13:10:43 +0000] [40] [INFO] Shutting down
brickserver             | [2021-07-22 13:10:43 +0000] [15] [INFO] Shutting down
brickserver             | [2021-07-22 13:10:43 +0000] [17] [INFO] Waiting for application shutdown.
brickserver             | [2021-07-22 13:10:43 +0000] [17] [INFO] Application shutdown complete.
brickserver             | [2021-07-22 13:10:43 +0000] [17] [INFO] Finished server process [17]
brickserver             | [2021-07-22 13:10:43 +0000] [17] [INFO] Worker exiting (pid: 17)
brickserver             | {"loglevel": "\"debug\"", "workers": 12, "bind": "0.0.0.0:80", "graceful_timeout": 120, "timeout": 120, "keepalive": 5, "errorlog": "-", "accesslog": "-", "workers_per_core": 1.0, "use_max_workers": null, "host": "0.0.0.0", "port": "80"}
brickserver             | init table
brickserver             | Timeseries Initialized
brickserver             | [2021-07-22 13:10:43 +0000] [26] [INFO] Waiting for application shutdown.
brickserver             | [2021-07-22 13:10:43 +0000] [26] [INFO] Application shutdown complete.
brickserver             | [2021-07-22 13:10:43 +0000] [26] [INFO] Finished server process [26]
brickserver             | [2021-07-22 13:10:43 +0000] [26] [INFO] Worker exiting (pid: 26)
brickserver             | {"loglevel": "\"debug\"", "workers": 12, "bind": "0.0.0.0:80", "graceful_timeout": 120, "timeout": 120, "keepalive": 5, "errorlog": "-", "accesslog": "-", "workers_per_core": 1.0, "use_max_workers": null, "host": "0.0.0.0", "port": "80"}
brickserver             | init table
brickserver             | Timeseries Initialized
brickserver             | [2021-07-22 13:10:43 +0000] [19] [INFO] Waiting for application shutdown.
brickserver             | [2021-07-22 13:10:43 +0000] [19] [INFO] Application shutdown complete.
brickserver             | [2021-07-22 13:10:43 +0000] [19] [INFO] Finished server process [19]
brickserver             | [2021-07-22 13:10:43 +0000] [19] [INFO] Worker exiting (pid: 19)
brickserver             | {"loglevel": "\"debug\"", "workers": 12, "bind": "0.0.0.0:80", "graceful_timeout": 120, "timeout": 120, "keepalive": 5, "errorlog": "-", "accesslog": "-", "workers_per_core": 1.0, "use_max_workers": null, "host": "0.0.0.0", "port": "80"}
brickserver             | init table
brickserver             | Timeseries Initialized
brickserver             | [2021-07-22 13:10:43 +0000] [24] [INFO] Waiting for application shutdown.
brickserver             | [2021-07-22 13:10:43 +0000] [24] [INFO] Application shutdown complete.
brickserver             | [2021-07-22 13:10:43 +0000] [24] [INFO] Finished server process [24]
brickserver             | [2021-07-22 13:10:43 +0000] [24] [INFO] Worker exiting (pid: 24)
brickserver             | {"loglevel": "\"debug\"", "workers": 12, "bind": "0.0.0.0:80", "graceful_timeout": 120, "timeout": 120, "keepalive": 5, "errorlog": "-", "accesslog": "-", "workers_per_core": 1.0, "use_max_workers": null, "host": "0.0.0.0", "port": "80"}
brickserver             | init table
brickserver             | Timeseries Initialized
brickserver             | [2021-07-22 13:10:43 +0000] [22] [INFO] Waiting for application shutdown.
brickserver             | [2021-07-22 13:10:43 +0000] [22] [INFO] Application shutdown complete.
brickserver             | [2021-07-22 13:10:43 +0000] [22] [INFO] Finished server process [22]
brickserver             | [2021-07-22 13:10:43 +0000] [22] [INFO] Worker exiting (pid: 22)
brickserver             | {"loglevel": "\"debug\"", "workers": 12, "bind": "0.0.0.0:80", "graceful_timeout": 120, "timeout": 120, "keepalive": 5, "errorlog": "-", "accesslog": "-", "workers_per_core": 1.0, "use_max_workers": null, "host": "0.0.0.0", "port": "80"}
brickserver             | [2021-07-22 13:10:43 +0000] [20] [INFO] Waiting for application shutdown.
brickserver             | [2021-07-22 13:10:43 +0000] [20] [INFO] Application shutdown complete.
brickserver             | [2021-07-22 13:10:43 +0000] [20] [INFO] Finished server process [20]
brickserver             | [2021-07-22 13:10:43 +0000] [20] [INFO] Worker exiting (pid: 20)
brickserver             | {"loglevel": "\"debug\"", "workers": 12, "bind": "0.0.0.0:80", "graceful_timeout": 120, "timeout": 120, "keepalive": 5, "errorlog": "-", "accesslog": "-", "workers_per_core": 1.0, "use_max_workers": null, "host": "0.0.0.0", "port": "80"}
brickserver             | init table
brickserver             | Timeseries Initialized
brickserver             | [2021-07-22 13:10:43 +0000] [13] [INFO] Waiting for application shutdown.
brickserver             | [2021-07-22 13:10:43 +0000] [13] [INFO] Application shutdown complete.
brickserver             | [2021-07-22 13:10:43 +0000] [13] [INFO] Finished server process [13]
brickserver             | [2021-07-22 13:10:43 +0000] [13] [INFO] Worker exiting (pid: 13)
brickserver             | {"loglevel": "\"debug\"", "workers": 12, "bind": "0.0.0.0:80", "graceful_timeout": 120, "timeout": 120, "keepalive": 5, "errorlog": "-", "accesslog": "-", "workers_per_core": 1.0, "use_max_workers": null, "host": "0.0.0.0", "port": "80"}
brickserver             | init table
brickserver             | Timeseries Initialized
brickserver             | [2021-07-22 13:10:43 +0000] [14] [INFO] Waiting for application shutdown.
brickserver             | [2021-07-22 13:10:43 +0000] [14] [INFO] Application shutdown complete.
brickserver             | [2021-07-22 13:10:43 +0000] [14] [INFO] Finished server process [14]
brickserver             | [2021-07-22 13:10:43 +0000] [14] [INFO] Worker exiting (pid: 14)
brickserver             | {"loglevel": "\"debug\"", "workers": 12, "bind": "0.0.0.0:80", "graceful_timeout": 120, "timeout": 120, "keepalive": 5, "errorlog": "-", "accesslog": "-", "workers_per_core": 1.0, "use_max_workers": null, "host": "0.0.0.0", "port": "80"}
brickserver             | init table
brickserver             | Timeseries Initialized
brickserver             | [2021-07-22 13:10:43 +0000] [23] [INFO] Waiting for application shutdown.
brickserver             | [2021-07-22 13:10:43 +0000] [23] [INFO] Application shutdown complete.
brickserver             | [2021-07-22 13:10:43 +0000] [23] [INFO] Finished server process [23]
brickserver             | [2021-07-22 13:10:43 +0000] [23] [INFO] Worker exiting (pid: 23)
brickserver             | {"loglevel": "\"debug\"", "workers": 12, "bind": "0.0.0.0:80", "graceful_timeout": 120, "timeout": 120, "keepalive": 5, "errorlog": "-", "accesslog": "-", "workers_per_core": 1.0, "use_max_workers": null, "host": "0.0.0.0", "port": "80"}
brickserver             | [2021-07-22 13:10:43 +0000] [40] [INFO] Waiting for application shutdown.
brickserver             | [2021-07-22 13:10:43 +0000] [40] [INFO] Application shutdown complete.
brickserver             | [2021-07-22 13:10:43 +0000] [40] [INFO] Finished server process [40]
brickserver             | [2021-07-22 13:10:43 +0000] [40] [INFO] Worker exiting (pid: 40)
brickserver             | {"loglevel": "\"debug\"", "workers": 12, "bind": "0.0.0.0:80", "graceful_timeout": 120, "timeout": 120, "keepalive": 5, "errorlog": "-", "accesslog": "-", "workers_per_core": 1.0, "use_max_workers": null, "host": "0.0.0.0", "port": "80"}
brickserver             | [2021-07-22 13:10:43 +0000] [15] [INFO] Waiting for application shutdown.
brickserver             | [2021-07-22 13:10:43 +0000] [15] [INFO] Application shutdown complete.
brickserver             | [2021-07-22 13:10:43 +0000] [15] [INFO] Finished server process [15]
brickserver             | [2021-07-22 13:10:43 +0000] [15] [INFO] Worker exiting (pid: 15)
brickserver             | {"loglevel": "\"debug\"", "workers": 12, "bind": "0.0.0.0:80", "graceful_timeout": 120, "timeout": 120, "keepalive": 5, "errorlog": "-", "accesslog": "-", "workers_per_core": 1.0, "use_max_workers": null, "host": "0.0.0.0", "port": "80"}
brickserver             | init table
brickserver             | Timeseries Initialized
brickserver             | [2021-07-22 13:10:44 +0000] [1] [INFO] Shutting down: Master
brickserver             | [2021-07-22 13:10:44 +0000] [1] [INFO] Reason: Worker failed to boot.
brickserver             | {"loglevel": "\"debug\"", "workers": 12, "bind": "0.0.0.0:80", "graceful_timeout": 120, "timeout": 120, "keepalive": 5, "errorlog": "-", "accesslog": "-", "workers_per_core": 1.0, "use_max_workers": null, "host": "0.0.0.0", "port": "80"}
brickserver exited with code 3
